# List documents by origin
POST http://localhost:9081/api/v1/documents
Content-Type: application/json

{
  "filter": "name==test",
  "sortBy": "test",
  "sortOrder": "ASC",
  "limit": 10
}

###
GET http://localhost:9081/api/v1/documents/684729ed3517ad329b15c43f